sudo: required

language: go

services:
  - docker

go:
  - master

before_install:
- docker pull lleseigneur/bonita-postgres
- docker run -d --name postgres -p 127.0.0.1:15432:5432 lleseigneur/bonita-postgres
- docker ps

script:
  - go get -t ./...
  - go build src/postgres-ping.go
  - go run src/postgres-ping.go "postgres" 15432 "bonita" "bonita" "bpm"
